### ISSUE TITLE
Ability Capsule does not work on pokemon without Hidden Abilities.

### ISSUE THREAD

**Issue by Spawnblade** [Jolkert/cobblemore#2]
Per title. The Ability Capsule (and not just the Patch) appears to check if the pokemon has a hidden ability before being allowed to be used on them (verified this by trying to use capsule - and failing - on an Alatian Sphinx. After giving it a random hidden ability via species additions, it suddenly let me apply capsule to them. Additionally tested this on two other mon.) Generally this is not an issue as few (if any) official pokemon have no hidden abilities (unless they only have a single ability, like a lot of legendaries.) However, this check makes it unusable on most, if not all, of the Alatian Fakemon pack, which does not seem to give any of its pokemon hidden abilities (but most have two standard abilities.) 

Would appreciate if the capsule could have its check for hidden abilities removed. Thanks!

**Comment by Jolkert** [comment]
HI! This issue slipped past me at first. The hidden ability check in the ability capsule is supposed to simply prevent the capsule from being used on a pokemon which currently has its hidden ability. did you get any message in chat when the capsule failed?

**Comment by Jolkert** [comment]
I found the issue. The check for a pokemon's hidden ability falsely asserted that a pokemon should always have a hidden ability. as stated, this isn't true, but went uncaught due to the fact that all vanilla pokemon without hidden abilities only have one ability, and therefore the capsule does not work on them either way. pushing a fix now
